# Generated by Django 4.2.10 on 2024-08-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("testcase_input", models.TextField()),
                ("testcase_output", models.TextField()),
                ("additional_testcase_input", models.TextField()),
                ("additional_testcase_output", models.TextField()),
                ("constraints", models.TextField()),
                ("editorial", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
