# Generated by Django 4.2.10 on 2024-08-11 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_alter_problem_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "problems",
                    models.ManyToManyField(
                        related_name="contests", to="dashboard.problem"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "temporary_username",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("code", models.TextField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(max_length=50)),
                ("score", models.IntegerField(default=0)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.problem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Leaderboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "temporary_username",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("total_score", models.IntegerField(default=0)),
                (
                    "contest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.contest",
                    ),
                ),
            ],
            options={
                "unique_together": {("contest", "temporary_username")},
            },
        ),
    ]
